# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags: [
  {id: 0, size: 0.113},
  {id: 1, size: 0.113},
  {id: 2, size: 0.113},
  {id: 3, size: 0.113},
  {id: 4, size: 0.113},
  {id: 5, size: 0.113},
  {id: 6, size: 0.113},
  {id: 7, size: 0.113},
  {id: 8, size: 0.113},
  {id: 9, size: 0.113},

  {id: 50, size: 0.09525},
  {id: 51, size: 0.09525},
  {id: 52, size: 0.09525},
  {id: 53, size: 0.09525},
  {id: 54, size: 0.09525},
  {id: 55, size: 0.09525},
  {id: 56, size: 0.09525},
  {id: 57, size: 0.09525},
  {id: 58, size: 0.09525},
  {id: 59, size: 0.09525},
  {id: 60, size: 0.09525},
  {id: 61, size: 0.09525},
  {id: 62, size: 0.09525},
  {id: 63, size: 0.09525},
  {id: 64, size: 0.09525},
  {id: 65, size: 0.09525},
  {id: 66, size: 0.09525},
  {id: 67, size: 0.09525},
  {id: 68, size: 0.09525},
  {id: 69, size: 0.09525},
  {id: 70, size: 0.09525},
  {id: 71, size: 0.09525},
  {id: 72, size: 0.09525},
  {id: 73, size: 0.09525},
  {id: 74, size: 0.09525},
  {id: 75, size: 0.09525},
  {id: 76, size: 0.09525},
  {id: 77, size: 0.09525},
  {id: 78, size: 0.09525},
  {id: 79, size: 0.09525},
  {id: 80, size: 0.09525},
  {id: 81, size: 0.09525},
  {id: 82, size: 0.09525},
  {id: 83, size: 0.09525},
  {id: 84, size: 0.09525},
  {id: 85, size: 0.09525},
  {id: 86, size: 0.09525},
  {id: 87, size: 0.09525},
  {id: 88, size: 0.09525},
  {id: 89, size: 0.09525},
]

# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
  ]
