# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags: [
  {id: 0, size: 0.065},
  {id: 1, size: 0.065},
  {id: 2, size: 0.065},
  {id: 3, size: 0.065},
  {id: 4, size: 0.065},
  {id: 5, size: 0.065},
  {id: 6, size: 0.065},
  {id: 7, size: 0.065},
  {id: 8, size: 0.065},
  {id: 9, size: 0.065},
  {id: 10, size: 0.065},
  {id: 11, size: 0.065},
  {id: 12, size: 0.065},
  {id: 13, size: 0.065},
  {id: 14, size: 0.065},
  {id: 15, size: 0.065},
  {id: 16, size: 0.065},
  {id: 17, size: 0.065},
  {id: 18, size: 0.065},
  {id: 19, size: 0.065},
  {id: 20, size: 0.065},
  {id: 21, size: 0.065},
  {id: 22, size: 0.065},
  {id: 23, size: 0.065},
  {id: 24, size: 0.065},
  {id: 25, size: 0.065},
  {id: 26, size: 0.065},
  {id: 27, size: 0.065},
  {id: 28, size: 0.065},
  {id: 29, size: 0.065},
  {id: 30, size: 0.065},
  {id: 31, size: 0.065},
  {id: 32, size: 0.065},
  {id: 33, size: 0.065},
  {id: 34, size: 0.065},
  {id: 35, size: 0.065},
  {id: 36, size: 0.065},
  {id: 37, size: 0.065},
  {id: 38, size: 0.065},
  {id: 39, size: 0.065},
  {id: 40, size: 0.065},
  {id: 41, size: 0.065},
  {id: 42, size: 0.065},
  {id: 43, size: 0.065},
  {id: 44, size: 0.065},
  {id: 45, size: 0.065},
  {id: 46, size: 0.065},
  {id: 47, size: 0.065},
  {id: 48, size: 0.065},
  {id: 49, size: 0.065},
  {id: 50, size: 0.065},
  {id: 51, size: 0.065},
  {id: 52, size: 0.065},
  {id: 53, size: 0.065},
  {id: 54, size: 0.065},
  {id: 55, size: 0.065},
  {id: 56, size: 0.065},
  {id: 57, size: 0.065},
  {id: 58, size: 0.065},
  {id: 59, size: 0.065},
  {id: 60, size: 0.065},
  {id: 61, size: 0.065},
  {id: 62, size: 0.065},
  {id: 63, size: 0.065},
  {id: 64, size: 0.065},
  {id: 65, size: 0.065},
  {id: 66, size: 0.065},
  {id: 67, size: 0.065},
  {id: 68, size: 0.065},
  {id: 69, size: 0.065},
  {id: 70, size: 0.065},
  {id: 71, size: 0.065},
  {id: 72, size: 0.065},
  {id: 73, size: 0.065},
  {id: 74, size: 0.065},
  {id: 75, size: 0.065},
  {id: 76, size: 0.065},
  {id: 77, size: 0.065},
  {id: 78, size: 0.065},
  {id: 79, size: 0.065},
  {id: 80, size: 0.065},
  {id: 81, size: 0.065},
  {id: 82, size: 0.065},
  {id: 83, size: 0.065},
  {id: 84, size: 0.065},
  {id: 85, size: 0.065},
  {id: 86, size: 0.065},
  {id: 87, size: 0.065},
  {id: 88, size: 0.065},
  {id: 89, size: 0.065},
  {id: 90, size: 0.065},
  {id: 91, size: 0.065},
  {id: 92, size: 0.065},
  {id: 93, size: 0.065},
  {id: 94, size: 0.065},
  {id: 95, size: 0.065},
  {id: 96, size: 0.065},
  {id: 97, size: 0.065},
  {id: 98, size: 0.065},
  {id: 99, size: 0.065},
  {id: 100, size: 0.065},
  {id: 101, size: 0.065},
  {id: 102, size: 0.065},
  {id: 103, size: 0.065},
  {id: 104, size: 0.065},
  {id: 105, size: 0.065},
  {id: 106, size: 0.065},
  {id: 107, size: 0.065},
  {id: 108, size: 0.065},
  {id: 109, size: 0.065},
  {id: 110, size: 0.065},
  {id: 111, size: 0.065},
  {id: 112, size: 0.065},
  {id: 113, size: 0.065},
  {id: 114, size: 0.065},
  {id: 115, size: 0.065},
  {id: 116, size: 0.065},
  {id: 117, size: 0.065},
  {id: 118, size: 0.065},
  {id: 119, size: 0.065},
  {id: 120, size: 0.065},
  {id: 121, size: 0.065},
  {id: 122, size: 0.065},
  {id: 123, size: 0.065},
  {id: 124, size: 0.065},
  {id: 125, size: 0.065},
  {id: 126, size: 0.065},
  {id: 127, size: 0.065},
  {id: 128, size: 0.065},
  {id: 129, size: 0.065},
  {id: 130, size: 0.065},
  {id: 131, size: 0.065},
  {id: 132, size: 0.065},
  {id: 133, size: 0.065},
  {id: 134, size: 0.065},
  {id: 135, size: 0.065},
  {id: 136, size: 0.065},
  {id: 137, size: 0.065},
  {id: 138, size: 0.065},
  {id: 139, size: 0.065},
  {id: 140, size: 0.065},
  {id: 141, size: 0.065},
  {id: 142, size: 0.065},
  {id: 143, size: 0.065},
  {id: 144, size: 0.065},
  {id: 145, size: 0.065},
  {id: 146, size: 0.065},
  {id: 147, size: 0.065},
  {id: 148, size: 0.065},
  {id: 149, size: 0.065},
  {id: 150, size: 0.065},
  {id: 151, size: 0.065},
  {id: 152, size: 0.065},
  {id: 153, size: 0.065},
  {id: 154, size: 0.065},
  {id: 155, size: 0.065},
  {id: 156, size: 0.065},
  {id: 157, size: 0.065},
  {id: 158, size: 0.065},
  {id: 159, size: 0.065},
  {id: 160, size: 0.065},
  {id: 161, size: 0.065},
  {id: 162, size: 0.065},
  {id: 163, size: 0.065},
  {id: 164, size: 0.065},
  {id: 165, size: 0.065},
  {id: 166, size: 0.065},
  {id: 167, size: 0.065},
  {id: 168, size: 0.065},
  {id: 169, size: 0.065},
  {id: 170, size: 0.065},
  {id: 171, size: 0.065},
  {id: 172, size: 0.065},
  {id: 173, size: 0.065},
  {id: 174, size: 0.065},
  {id: 175, size: 0.065},
  {id: 176, size: 0.065},
  {id: 177, size: 0.065},
  {id: 178, size: 0.065},
  {id: 179, size: 0.065},
  {id: 180, size: 0.065},
  {id: 181, size: 0.065},
  {id: 182, size: 0.065},
  {id: 183, size: 0.065},
  {id: 184, size: 0.065},
  {id: 185, size: 0.065},
  {id: 186, size: 0.065},
  {id: 187, size: 0.065},
  {id: 188, size: 0.065},
  {id: 189, size: 0.065},
  {id: 190, size: 0.065},
  {id: 191, size: 0.065},
  {id: 192, size: 0.065},
  {id: 193, size: 0.065},
  {id: 194, size: 0.065},
  {id: 195, size: 0.065},
  {id: 196, size: 0.065},
  {id: 197, size: 0.065},
  {id: 198, size: 0.065},
  {id: 199, size: 0.065},
  {id: 200, size: 0.065},
  {id: 201, size: 0.065},
  {id: 202, size: 0.065},
  {id: 203, size: 0.065},
  {id: 204, size: 0.065},
  {id: 205, size: 0.065},
  {id: 206, size: 0.065},
  {id: 207, size: 0.065},
  {id: 208, size: 0.065},
  {id: 209, size: 0.065},
  {id: 210, size: 0.065},
  {id: 211, size: 0.065},
  {id: 212, size: 0.065},
  {id: 213, size: 0.065},
  {id: 214, size: 0.065},
  {id: 215, size: 0.065},
  {id: 216, size: 0.065},
  {id: 217, size: 0.065},
  {id: 218, size: 0.065},
  {id: 219, size: 0.065},
  {id: 220, size: 0.065},
  {id: 221, size: 0.065},
  {id: 222, size: 0.065},
  {id: 223, size: 0.065},
  {id: 224, size: 0.065},
  {id: 225, size: 0.065},
  {id: 226, size: 0.065},
  {id: 227, size: 0.065},
  {id: 228, size: 0.065},
  {id: 229, size: 0.065},
  {id: 230, size: 0.065},
  {id: 231, size: 0.065},
  {id: 232, size: 0.065},
  {id: 233, size: 0.065},
  {id: 234, size: 0.065},
  {id: 235, size: 0.065},
  {id: 236, size: 0.065},
  {id: 237, size: 0.065},
  {id: 238, size: 0.065},
  {id: 239, size: 0.065},
  {id: 240, size: 0.065},
  {id: 241, size: 0.065},
  {id: 242, size: 0.065},
  {id: 243, size: 0.065},
  {id: 244, size: 0.065},
  {id: 245, size: 0.065},
  {id: 246, size: 0.065},
  {id: 247, size: 0.065},
  {id: 248, size: 0.065},
  {id: 249, size: 0.065},
  {id: 250, size: 0.065},
  {id: 251, size: 0.065},
  {id: 252, size: 0.065},
  {id: 253, size: 0.065},
  {id: 254, size: 0.065},
  {id: 255, size: 0.065},
  {id: 256, size: 0.065},
  {id: 257, size: 0.065},
  {id: 258, size: 0.065},
  {id: 259, size: 0.065},
  {id: 260, size: 0.065},
  {id: 261, size: 0.065},
  {id: 262, size: 0.065},
  {id: 263, size: 0.065},
  {id: 264, size: 0.065},
  {id: 265, size: 0.065},
  {id: 266, size: 0.065},
  {id: 267, size: 0.065},
  {id: 268, size: 0.065},
  {id: 269, size: 0.065},
  {id: 270, size: 0.065},
  {id: 271, size: 0.065},
  {id: 272, size: 0.065},
  {id: 273, size: 0.065},
  {id: 274, size: 0.065},
  {id: 275, size: 0.065},
  {id: 276, size: 0.065},
  {id: 277, size: 0.065},
  {id: 278, size: 0.065},
  {id: 279, size: 0.065},
  {id: 280, size: 0.065},
  {id: 281, size: 0.065},
  {id: 282, size: 0.065},
  {id: 283, size: 0.065},
  {id: 284, size: 0.065},
  {id: 285, size: 0.065},
  {id: 286, size: 0.065},
  {id: 287, size: 0.065},
  {id: 288, size: 0.065},
  {id: 289, size: 0.065},
  {id: 290, size: 0.065},
  {id: 291, size: 0.065},
  {id: 292, size: 0.065},
  {id: 293, size: 0.065},
  {id: 294, size: 0.065},
  {id: 295, size: 0.065},
  {id: 296, size: 0.065},
  {id: 297, size: 0.065},
  {id: 298, size: 0.065},
  {id: 299, size: 0.065},
  {id: 300, size: 0.065},
  {id: 301, size: 0.065},
  {id: 302, size: 0.065},
  {id: 303, size: 0.065},
  {id: 304, size: 0.065},
  {id: 305, size: 0.065},
  {id: 306, size: 0.065},
  {id: 307, size: 0.065},
  {id: 308, size: 0.065},
  {id: 309, size: 0.065},
  {id: 310, size: 0.065},
  {id: 311, size: 0.065},
  {id: 312, size: 0.065},
  {id: 313, size: 0.065},
  {id: 314, size: 0.065},
  {id: 315, size: 0.065},
  {id: 316, size: 0.065},
  {id: 317, size: 0.065},
  {id: 318, size: 0.065},
  {id: 319, size: 0.065},
  {id: 320, size: 0.065},
  {id: 321, size: 0.065},
  {id: 322, size: 0.065},
  {id: 323, size: 0.065},
  {id: 324, size: 0.065},
  {id: 325, size: 0.065},
  {id: 326, size: 0.065},
  {id: 327, size: 0.065},
  {id: 328, size: 0.065},
  {id: 329, size: 0.065},
  {id: 330, size: 0.065},
  {id: 331, size: 0.065},
  {id: 332, size: 0.065},
  {id: 333, size: 0.065},
  {id: 334, size: 0.065},
  {id: 335, size: 0.065},
  {id: 336, size: 0.065},
  {id: 337, size: 0.065},
  {id: 338, size: 0.065},
  {id: 339, size: 0.065},
  {id: 340, size: 0.065},
  {id: 341, size: 0.065},
  {id: 342, size: 0.065},
  {id: 343, size: 0.065},
  {id: 344, size: 0.065},
  {id: 345, size: 0.065},
  {id: 346, size: 0.065},
  {id: 347, size: 0.065},
  {id: 348, size: 0.065},
  {id: 349, size: 0.065},
  {id: 350, size: 0.065},
  {id: 351, size: 0.065},
  {id: 352, size: 0.065},
  {id: 353, size: 0.065},
  {id: 354, size: 0.065},
  {id: 355, size: 0.065},
  {id: 356, size: 0.065},
  {id: 357, size: 0.065},
  {id: 358, size: 0.065},
  {id: 359, size: 0.065},
  {id: 360, size: 0.065},
  {id: 361, size: 0.065},
  {id: 362, size: 0.065},
  {id: 363, size: 0.065},
  {id: 364, size: 0.065},
  {id: 365, size: 0.065},
  {id: 366, size: 0.065},
  {id: 367, size: 0.065},
  {id: 368, size: 0.065},
  {id: 369, size: 0.065},
  {id: 370, size: 0.065},
  {id: 371, size: 0.065},
  {id: 372, size: 0.065},
  {id: 373, size: 0.065},
  {id: 374, size: 0.065},
  {id: 375, size: 0.065},
  {id: 376, size: 0.065},
  {id: 377, size: 0.065},
  {id: 378, size: 0.065},
  {id: 379, size: 0.065},
  {id: 380, size: 0.065},
  {id: 381, size: 0.065},
  {id: 382, size: 0.065},
  {id: 383, size: 0.065},
  {id: 384, size: 0.065},
  {id: 385, size: 0.065},
  {id: 386, size: 0.065},
  {id: 387, size: 0.065},
  {id: 388, size: 0.065},
  {id: 389, size: 0.065},
  {id: 390, size: 0.065},
  {id: 391, size: 0.065},
  {id: 392, size: 0.065},
  {id: 393, size: 0.065},
  {id: 394, size: 0.065},
  {id: 395, size: 0.065},
  {id: 396, size: 0.065},
  {id: 397, size: 0.065},
  {id: 398, size: 0.065},
  {id: 399, size: 0.065},
  {id: 400, size: 0.065},
  {id: 401, size: 0.065},
  {id: 402, size: 0.065},
  {id: 403, size: 0.065},
  {id: 404, size: 0.065},
  {id: 405, size: 0.065},
  {id: 406, size: 0.065},
  {id: 407, size: 0.065},
  {id: 408, size: 0.065},
  {id: 409, size: 0.065},
  {id: 410, size: 0.065},
  {id: 411, size: 0.065},
  {id: 412, size: 0.065},
  {id: 413, size: 0.065},
  {id: 414, size: 0.065},
  {id: 415, size: 0.065},
  {id: 416, size: 0.065},
  {id: 417, size: 0.065},
  {id: 418, size: 0.065},
  {id: 419, size: 0.065},
  {id: 420, size: 0.065},
  {id: 421, size: 0.065},
  {id: 422, size: 0.065},
  {id: 423, size: 0.065},
  {id: 424, size: 0.065},
  {id: 425, size: 0.065},
  {id: 426, size: 0.065},
  {id: 427, size: 0.065},
  {id: 428, size: 0.065},
  {id: 429, size: 0.065},
  {id: 430, size: 0.065},
  {id: 431, size: 0.065},
  {id: 432, size: 0.065},
  {id: 433, size: 0.065},
  {id: 434, size: 0.065},
  {id: 435, size: 0.065},
  {id: 436, size: 0.065},
  {id: 437, size: 0.065},
  {id: 438, size: 0.065},
  {id: 439, size: 0.065},
  {id: 440, size: 0.065},
  {id: 441, size: 0.065},
  {id: 442, size: 0.065},
  {id: 443, size: 0.065},
  {id: 444, size: 0.065},
  {id: 445, size: 0.065},
  {id: 446, size: 0.065},
  {id: 447, size: 0.065},
  {id: 448, size: 0.065},
  {id: 449, size: 0.065},
  {id: 450, size: 0.065},
  {id: 451, size: 0.065},
  {id: 452, size: 0.065},
  {id: 453, size: 0.065},
  {id: 454, size: 0.065},
  {id: 455, size: 0.065},
  {id: 456, size: 0.065},
  {id: 457, size: 0.065},
  {id: 458, size: 0.065},
  {id: 459, size: 0.065},
  {id: 460, size: 0.065},
  {id: 461, size: 0.065},
  {id: 462, size: 0.065},
  {id: 463, size: 0.065},
  {id: 464, size: 0.065},
  {id: 465, size: 0.065},
  {id: 466, size: 0.065},
  {id: 467, size: 0.065},
  {id: 468, size: 0.065},
  {id: 469, size: 0.065},
  {id: 470, size: 0.065},
  {id: 471, size: 0.065},
  {id: 472, size: 0.065},
  {id: 473, size: 0.065},
  {id: 474, size: 0.065},
  {id: 475, size: 0.065},
  {id: 476, size: 0.065},
  {id: 477, size: 0.065},
  {id: 478, size: 0.065},
  {id: 479, size: 0.065},
  {id: 480, size: 0.065},
  {id: 481, size: 0.065},
  {id: 482, size: 0.065},
  {id: 483, size: 0.065},
  {id: 484, size: 0.065},
  {id: 485, size: 0.065},
  {id: 486, size: 0.065},
  {id: 487, size: 0.065},
  {id: 488, size: 0.065},
  {id: 489, size: 0.065},
  {id: 490, size: 0.065},
  {id: 491, size: 0.065},
  {id: 492, size: 0.065},
  {id: 493, size: 0.065},
  {id: 494, size: 0.065},
  {id: 495, size: 0.065},
  {id: 496, size: 0.065},
  {id: 497, size: 0.065},
  {id: 498, size: 0.065},
  {id: 499, size: 0.065},
  {id: 500, size: 0.065},
  {id: 501, size: 0.065},
  {id: 502, size: 0.065},
  {id: 503, size: 0.065},
  {id: 504, size: 0.065},
  {id: 505, size: 0.065},
  {id: 506, size: 0.065},
  {id: 507, size: 0.065},
  {id: 508, size: 0.065},
  {id: 509, size: 0.065},
  {id: 510, size: 0.065},
  {id: 511, size: 0.065},
  {id: 512, size: 0.065},
  {id: 513, size: 0.065},
  {id: 514, size: 0.065},
  {id: 515, size: 0.065},
  {id: 516, size: 0.065},
  {id: 517, size: 0.065},
  {id: 518, size: 0.065},
  {id: 519, size: 0.065},
  {id: 520, size: 0.065},
  {id: 521, size: 0.065},
  {id: 522, size: 0.065},
  {id: 523, size: 0.065},
  {id: 524, size: 0.065},
  {id: 525, size: 0.065},
  {id: 526, size: 0.065},
  {id: 527, size: 0.065},
  {id: 528, size: 0.065},
  {id: 529, size: 0.065},
  {id: 530, size: 0.065},
  {id: 531, size: 0.065},
  {id: 532, size: 0.065},
  {id: 533, size: 0.065},
  {id: 534, size: 0.065},
  {id: 535, size: 0.065},
  {id: 536, size: 0.065},
  {id: 537, size: 0.065},
  {id: 538, size: 0.065},
  {id: 539, size: 0.065},
  {id: 540, size: 0.065},
  {id: 541, size: 0.065},
  {id: 542, size: 0.065},
  {id: 543, size: 0.065},
  {id: 544, size: 0.065},
  {id: 545, size: 0.065},
  {id: 546, size: 0.065},
  {id: 547, size: 0.065},
  {id: 548, size: 0.065},
  {id: 549, size: 0.065},
  {id: 550, size: 0.065},
  {id: 551, size: 0.065},
  {id: 552, size: 0.065},
  {id: 553, size: 0.065},
  {id: 554, size: 0.065},
  {id: 555, size: 0.065},
  {id: 556, size: 0.065},
  {id: 557, size: 0.065},
  {id: 558, size: 0.065},
  {id: 559, size: 0.065},
  {id: 560, size: 0.065},
  {id: 561, size: 0.065},
  {id: 562, size: 0.065},
  {id: 563, size: 0.065},
  {id: 564, size: 0.065},
  {id: 565, size: 0.065},
  {id: 566, size: 0.065},
  {id: 567, size: 0.065},
  {id: 568, size: 0.065},
  {id: 569, size: 0.065},
  {id: 570, size: 0.065},
  {id: 571, size: 0.065},
  {id: 572, size: 0.065},
  {id: 573, size: 0.065},
  {id: 574, size: 0.065},
  {id: 575, size: 0.065},
  {id: 576, size: 0.065},
  {id: 577, size: 0.065},
  {id: 578, size: 0.065},
  {id: 579, size: 0.065},
  {id: 580, size: 0.065},
  {id: 581, size: 0.065},
  {id: 582, size: 0.065},
  {id: 583, size: 0.065},
  {id: 584, size: 0.065},
  {id: 585, size: 0.065},
  {id: 586, size: 0.065}
]

# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
  ]
